version: '3.8'
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    pull_policy: always
    ports:
      - '3210:3210'
    environment:
      OPENAI_API_KEY: FakeKey  # 传入的 API Key
      OPENAI_PROXY_URL: https://api-proxy.com/v1
      ACCESS_CODE: lobe66