Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
    - TemplateName: ECS单机版
      SupportOperations:
      - Start
      - Stop
      - Restart
    SupportBackup: true
    ModifyParametersConfig:
    - TemplateName: ECS单机版
      Operation:
      - Name: 变更ECS实例密码
        Description: 变更ECS实例密码
        Type: Custom
        Parameters:
        - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      ArtifactRelation:
        ecs_image_quickstart-LobeChat:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
      SupplierTemplateConfigs:
      - Name: ECS单机版
        Url: ros_templates/template.yaml
        PredefinedParameters:
        - Name: 试用套餐
          Parameters:
            EcsInstanceType:
            - ecs.u1-c1m1.large
            PayType: PostPaid
            VpcOption: ExistingVPC
          OrderList:
          - EcsInstanceType
          - PayType
          - VpcOption
          TrialType: TrialOnly
          Type: Normal
        AllowedRegions:
        - ap-southeast-1
        - cn-hangzhou
        - cn-huhehaote
        - cn-shanghai
        - cn-qingdao
        - cn-beijing
        - cn-zhangjiakou
        - cn-wulanchabu
        - cn-shenzhen
        - cn-heyuan
        - cn-guangzhou
        - cn-chengdu
        - cn-hongkong
        - ap-southeast-3
        - ap-southeast-5
        - ap-southeast-6
        - ap-southeast-7
        - ap-northeast-1
        - ap-northeast-2
        - eu-central-1
        - eu-west-1
        - us-west-1
        - us-east-1
        - me-central-1
        - me-east-1
    TemplateConfigs:
    - Name: ECS单机版
      Url: ros_templates/template.yaml
      AllowedRegions:
      - ap-southeast-1
      PredefinedParameters:
      - Name: 试用套餐
        Parameters:
          EcsInstanceType:
          - ecs.u1-c1m1.large
          PayType: PostPaid
          VpcOption: ExistingVPC
        OrderList:
        - EcsInstanceType
        - PayType
        - VpcOption
        TrialType: TrialOnly
        Type: Normal
      TrialHiddenParameterKeys:
      - VpcId
      - PayPeriod
      - VSwitchId
      - PayPeriodUnit
      - PayType
      CreateFromExistInstanceParameterKeys:
      - VpcId
      - PayPeriod
      - VSwitchId
      - VpcOption
      - PayPeriodUnit
      - PayType
  ServiceType: private
  ServiceInfo:
  - Locale: zh-CN
    Name: LobeChat社区版
    ShortDescription: "现代化设计的开源 ChatGPT/LLMs 聊天应用与开发框架\n支持语音合成、多模态、可扩展的（function call）插件系统\n\
      \ 一键免费拥有你自己的 ChatGPT/Gemini/Claude/Ollama 应用"
    Image: 
      https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1853370294850618/service-image/54252293-582f-42bd-8e72-4c8ab7c446e0.png
    Softwares:
    - Name: LobeChat
      Version: v2.2.10
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_quickstart-LobeChat
    Description: quickstart-LobeChat EcsImage
    SupportRegionIds:
    - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: LYH-RAIN
        RepoName: aliyun-computenest/quickstart-LobeChat
        Branch: ecs-image
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      CommandContent: 'mkdir -p /root/application

        if [ -e "/root/code/.env" ]; then cp -r "/root/code/.env" "/root/application/";
        fi

        if [ -e "/root/code/docker-compose.yaml" ]; then cp -r "/root/code/docker-compose.yaml"
        "/root/application/"; fi

        if [ -e "/root/code/mock-market.js" ]; then cp -r "/root/code/mock-market.js"
        "/root/application/"; fi

        cd /root/application

        sed -i ''s/pull_policy: always/pull_policy: if_not_present/g'' docker-compose.yaml

        docker compose -f docker-compose.yaml build

        docker compose -f docker-compose.yaml pull || true;'
